<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Module 14 | Summer R Bootcamp</title>
<meta name="author" content="Alex Pijyan">
<meta name="description" content="  Modeling  Introduction Patterns in your data provide clues about relationships among variables. If a systematic relationship exists between two variables it will appear as a pattern in the data....">
<meta name="generator" content="bookdown 0.41 with bs4_book()">
<meta property="og:title" content="Module 14 | Summer R Bootcamp">
<meta property="og:type" content="book">
<meta property="og:description" content="  Modeling  Introduction Patterns in your data provide clues about relationships among variables. If a systematic relationship exists between two variables it will appear as a pattern in the data....">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Module 14 | Summer R Bootcamp">
<meta name="twitter:description" content="  Modeling  Introduction Patterns in your data provide clues about relationships among variables. If a systematic relationship exists between two variables it will appear as a pattern in the data....">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.8.0/transition.js"></script><script src="libs/bs3compat-0.8.0/tabs.js"></script><script src="libs/bs3compat-0.8.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<link rel="stylesheet" href="style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Summer R Bootcamp</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Welcome</a></li>
<li class="book-part">Week 1</li>
<li><a class="" href="introduction.html">Introduction</a></li>
<li><a class="" href="module-1.html">Module 1</a></li>
<li><a class="" href="module-2.html">Module 2</a></li>
<li><a class="" href="module-3.html">Module 3</a></li>
<li><a class="" href="module-4.html">Module 4</a></li>
<li><a class="" href="problem-set-1.html">Problem Set 1</a></li>
<li><a class="" href="ps-1-solutions.html">PS 1 Solutions</a></li>
<li class="book-part">Week 2</li>
<li><a class="" href="module-5.html">Module 5</a></li>
<li><a class="" href="module-6.html">Module 6</a></li>
<li><a class="" href="module-7.html">Module 7</a></li>
<li><a class="" href="problem-set-2.html">Problem Set 2</a></li>
<li><a class="" href="ps-2-solutions.html">PS 2 Solutions</a></li>
<li class="book-part">Week 3</li>
<li><a class="" href="module-8.html">Module 8</a></li>
<li><a class="" href="module-9.html">Module 9</a></li>
<li><a class="" href="module-10.html">Module 10</a></li>
<li><a class="" href="module-11.html">Module 11</a></li>
<li><a class="" href="problem-set-3.html">Problem Set 3</a></li>
<li><a class="" href="ps-3-solutions.html">PS 3 Solutions</a></li>
<li class="book-part">Week 4</li>
<li><a class="" href="module-12.html">Module 12</a></li>
<li><a class="" href="module-13.html">Module 13</a></li>
<li><a class="active" href="module-14.html">Module 14</a></li>
<li><a class="" href="problem-set-4.html">Problem Set 4</a></li>
<li><a class="" href="ps-4-solutions.html">PS 4 Solutions</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/rstudio/bookdown-demo">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="module-14" class="section level1 unnumbered">
<h1>Module 14<a class="anchor" aria-label="anchor" href="#module-14"><i class="fas fa-link"></i></a>
</h1>
<p> </p>
<div id="modeling" class="section level2 unnumbered">
<h2>Modeling<a class="anchor" aria-label="anchor" href="#modeling"><i class="fas fa-link"></i></a>
</h2>
<div id="introduction-2" class="section level3 unnumbered">
<h3>Introduction<a class="anchor" aria-label="anchor" href="#introduction-2"><i class="fas fa-link"></i></a>
</h3>
<p>Patterns in your data provide clues about relationships among variables. If a systematic relationship exists between two variables it will appear as a pattern in the data. If you spot a pattern, ask yourself:</p>
<ul>
<li>Could this pattern be due to coincidence (i.e. random chance)?</li>
<li>How can you describe the relationship implied by the pattern?</li>
<li>How strong is the relationship implied by the pattern?</li>
<li>What other variables might affect the relationship?</li>
<li>Does the relationship change if you look at individual subgroups of the data?</li>
</ul>
<p>Patterns provide one of the most useful tools for data analysts because they reveal <strong>covariation</strong>. If you think of <strong>variation</strong> as a phenomenon that creates uncertainty, <strong>covariation</strong> is a phenomenon that reduces it. If two variables covary, you can use the values of one variable to make better predictions about the values of the second. If the covariation is due to a causal relationship (a special case), then you can use the value of one variable to control the value of the second.</p>
<p><strong>Models</strong> are a tool for extracting patterns out of data. The goal of a model is to provide a simple low-dimensional summary of a dataset. Ideally, the model will capture true “signals” (i.e. patterns generated by the phenomenon of interest), and ignore “noise” (i.e. random variation that you’re not interested in).</p>
<p>In this module, we only cover <strong>predictive models</strong>, which, as the name suggests, generate predictions. Specifically, we are going to focus on linear regression models, which are the most famous and arguably the simplest models, but yet they are widely used in all of statistics.</p>
<p> </p>
</div>
<div id="simple-linear-regression-slr-model" class="section level3 unnumbered">
<h3>Simple Linear Regression (SLR) Model<a class="anchor" aria-label="anchor" href="#simple-linear-regression-slr-model"><i class="fas fa-link"></i></a>
</h3>
<p>As mentioned, a <strong>linear regression model</strong> is one of the simplest models for doing data analysis. Though it may seem somewhat dull compared to some of the more modern statistical learning approaches, linear regression is still a useful and widely applied statistical learning method.</p>
<p>Moreover, it serves as a good starting point for more advanced approaches; in fact, many of the more sophisticated statistical learning approaches can be seen as generalizations to or extensions of ordinary linear regression. Consequently, it is important to have a good understanding of linear regression before studying more complex learning methods.</p>
<p>Before discussing linear regression models more in detail, we will first give its general definition. We will start off with a <strong>simple linear regression (SLR) model</strong>, a linear model that contains only one predictor.</p>
<div id="model-set-up" class="section level4 unnumbered">
<h4>Model Set Up<a class="anchor" aria-label="anchor" href="#model-set-up"><i class="fas fa-link"></i></a>
</h4>
<p>A simple linear regression model defines a relationship between two variables as follows:</p>
<p> </p>
<p><span class="math display">\[\begin{align*}
Y_i = \beta_0 + \beta_1 X_i + \epsilon_i \quad  for  \quad  i = 1, \dots, n
\end{align*}\]</span></p>
<p> </p>
<p>where</p>
<ul>
<li>
<span class="math inline">\(Y\)</span> is the <strong>response</strong> (also known as <strong>target</strong>, <strong>outcome</strong>, and <strong>dependent</strong>) variable</li>
<li>
<span class="math inline">\(X\)</span> is the <strong>predictor</strong> (also known as <strong>explanatory</strong> and <strong>independent</strong>) variable and its values are <strong>fixed</strong>
</li>
<li>
<span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are the <strong>fixed model parameters</strong>; specifically, an <strong>intercept</strong> and <strong>slope</strong> of the regression function, respectively</li>
<li>
<span class="math inline">\(\epsilon\)</span> (epsilon) is an error term and it’s a <strong>random variable</strong>; it is assumed to be normally distributed with mean 0 and variance <span class="math inline">\(\sigma^2\)</span>, that is, <span class="math inline">\(\epsilon \sim N(0, \sigma^2)\)</span>.</li>
</ul>
<p> </p>
<p>This model is <strong>linear</strong>, because it uses a linear function to describe a relationship between the response and predictor variables. And it is <strong>simple</strong>, because it contains only one predictor.</p>
<p> </p>
<p><strong>Interpretation of parameters:</strong></p>
<p>The slope parameter <span class="math inline">\(\beta_1\)</span> indicates the change in the mean value of response variable <span class="math inline">\(Y\)</span> per unit increase in the predictor variable <span class="math inline">\(X\)</span>.</p>
<p>The intercept parameter <span class="math inline">\(\beta_0\)</span> is the <span class="math inline">\(Y\)</span> intercept of the regression line. When the scope of the model includes <span class="math inline">\(X = 0\)</span>, then <span class="math inline">\(\beta_0\)</span> given the mean value of <span class="math inline">\(Y\)</span> at <span class="math inline">\(X = 0\)</span>.</p>
<p> </p>
<p><strong>Model Assumptions:</strong></p>
<p>Linear regression models must meet certain assumptions to be valid. These assumptions are</p>
<ul>
<li>Linearity of the regression function</li>
<li>Constant variance of the error terms</li>
<li>Independence of the error terms</li>
<li>No outliers</li>
<li>Normality of the error terms</li>
</ul>
<p> </p>
<p>If we assume that the relationship between variables can be described using the SLR model, then this model can be utilized to make predictions about the response variable <span class="math inline">\(Y\)</span> based on the values of the predictor variable <span class="math inline">\(X\)</span>.</p>
<p>Normally, we make predictions about the mean value of the response variable. In other words, using the predictive models such as SLR, we predict what the average value of the response value would be for a given value of the explanatory variable. It can be written as</p>
<p> </p>
<p><span class="math display">\[\begin{align*}
E(Y_i) = E(\beta_0 + \beta_1 X_i + \epsilon_i) = \beta_0 + \beta_1 X_i + 0  = \beta_0 + \beta_1 X_i
\end{align*}\]</span></p>
<p>Thus,</p>
<p><span class="math display">\[\begin{align*}
E(Y_i) = \beta_0 + \beta_1 X_i  \quad  for  \quad  i = 1, \dots, n
\end{align*}\]</span></p>
<p> </p>
<p>As you noticed, SLR model contains three parameters: <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span>, and <span class="math inline">\(\sigma^2\)</span>. These parameters are fixed (they are constant), but their are <strong>unknown</strong> to us. Thus, we first need to estimate these parameters in order to set up a model and make predictions based on this model.</p>
<p> </p>
</div>
<div id="parameter-estimation-least-squares-approach" class="section level4 unnumbered">
<h4>Parameter Estimation: Least Squares Approach<a class="anchor" aria-label="anchor" href="#parameter-estimation-least-squares-approach"><i class="fas fa-link"></i></a>
</h4>
<p>Before we introduce the estimation method, let’s consider an example. Recall the lung capacity dataset that we’ve used in other modules. Suppose you believe that an SLR model can be used to predict <em>lung capacity</em> based on patient’s <em>height</em>. As adviced earlier, it is always a good idea to visualize your data as a part of EDA (Explanatory Data Analysis):</p>
<div class="sourceCode" id="cb495"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span> <span class="va">gg</span> <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">dataset1</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Height</span>, y <span class="op">=</span> <span class="va">LungCap</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"steelblue"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Lung Capacity versus Height"</span>,</span>
<span>       </span>
<span>       subtitle <span class="op">=</span> <span class="st">"From lung_capacity dataset"</span>,</span>
<span>       </span>
<span>       x <span class="op">=</span> <span class="st">"Height"</span>,</span>
<span>       </span>
<span>       y <span class="op">=</span> <span class="st">"Lung Capacity"</span><span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">gg</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="Module_14_files/figure-html/unnamed-chunk-2-1.png" width="672"></div>
<p>From the scatterplot it becomes clear that a linear model will indeed be a good fit to our data as it displays a strong linear pattern/trend. Now it’s time to estimate the parameters and set up the model.</p>
<p>But how can we estimate these parameters? In general, our goal is to build a predictive model (known as a <strong>fitted model</strong>) of the form</p>
<p> </p>
<p><span class="math display">\[\begin{align*}
\hat{Y} = b_0 + b_1X
\end{align*}\]</span></p>
<p> </p>
<p>where <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> are the estimates of the model parameters <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, respectively, and <span class="math inline">\(\hat{Y}\)</span> is the <strong>fitted value</strong> of the response variable. There are infinite number of combinations of <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> values. And these combinations define a family of predictive models.</p>
<p>Let’s plot some of them. For example, we could try to model the data with a horizontal line representing the mean value of the <em>lung capacity</em> variable. That is, we are building a model where the response outcome does not depend on the predictor variable:</p>
<div class="sourceCode" id="cb496"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="va">mean_lungcap</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">dataset1</span><span class="op">$</span><span class="va">LungCap</span><span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="va">gg</span> <span class="op">+</span> </span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="va">mean_lungcap</span>, size <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="co">#&gt; Warning: Using `size` aesthetic for lines was deprecated in ggplot2</span></span>
<span><span class="co">#&gt; 3.4.0.</span></span>
<span><span class="co">#&gt; ℹ Please use `linewidth` instead.</span></span>
<span><span class="co">#&gt; This warning is displayed once every 8 hours.</span></span>
<span><span class="co">#&gt; Call `lifecycle::last_lifecycle_warnings()` to see where</span></span>
<span><span class="co">#&gt; this warning was generated.</span></span></code></pre></div>
<div class="inline-figure"><img src="Module_14_files/figure-html/unnamed-chunk-3-1.png" width="672"></div>
<p>In the plot above, we see this doesn’t seem to do a very good job. Many of the data points are very far from the line representing the mean value of the response variable. This is an example of <strong>underfitting</strong>. The obvious fix is to make the fitted model actually depend on the predictor. Below we illustrate a few of these models:</p>
<div class="sourceCode" id="cb497"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">4</span><span class="op">)</span></span>
<span><span class="va">models</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span></span>
<span>  b0 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">250</span>, <span class="op">-</span><span class="fl">20</span>, <span class="fl">40</span><span class="op">)</span>,</span>
<span>  b1 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">250</span>, <span class="op">-</span><span class="fl">5</span>, <span class="fl">5</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="va">gg</span> <span class="op">+</span></span>
<span>  </span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_abline</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>intercept <span class="op">=</span> <span class="va">b0</span>, slope <span class="op">=</span> <span class="va">b1</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">models</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="Module_14_files/figure-html/unnamed-chunk-4-1.png" width="672"></div>
<p>Each line on the plot represents a fitted model. There are 250 models on the plot (not all of them are depicted on the plot). Most of these models are really bad! But how are we going to decide which one is the best? And what should be the selection criterion?</p>
<p>We need to find the good models by making precise our intuition that a good model is “close” to the data. We need a way to quantify the distance between the data and a model. Then we can fit the model by finding the value of <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> that generate the model with the smallest distance from this data.</p>
<p>One easy place to start is to find the vertical distance between each point and the model. This distance is just the difference between the fitted value (predicted) given by the model and the actual response value in the data:</p>
<p><span class="math display">\[\begin{align*}
Y_i - \hat{Y}_i
\end{align*}\]</span></p>
<pre><code>#&gt; `geom_smooth()` using formula = 'y ~ x'</code></pre>
<div class="inline-figure"><img src="Module_14_files/figure-html/unnamed-chunk-5-1.png" width="672"></div>
<p>Next, we need some way to compute an overall distance between the predicted and actual values. One common way to do this in statistics is to use the sum of squared deviations (also known as <strong>Error Sum of Squares (SSE)</strong>). We compute the difference between actual and predicted, square them, and add them up:</p>
<p> </p>
<p><span class="math display">\[\begin{align*}
SSE = \sum_{i = 1}^{n}(Y_i - \hat{Y}_i)^2 = \sum_{i = 1}^{n}(Y_i - (b_0 + b_1X_i))^2
\end{align*}\]</span></p>
<p> </p>
<p>This distance has lots of appealing mathematical properties, which we’re not going to talk about here.</p>
<p>Now a pair of values <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> that minimize the quantity given above are known to be the best estimates of the model parameters <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>. This approach is known as the <strong>least squares method</strong>, the estimates are called <strong>least squares estimates</strong>, and the fitted model is referred to as <strong>ordinary least squares (OLS) regression</strong>.</p>
<p>We will skip the derivation of these estimates as it is beyond the scope of this bootcamp and simply provide formulas:</p>
<p> </p>
<p><span class="math display">\[\begin{align*}
b_1 = \frac{\sum_{i = 1}^{n}(x_i - \bar{x})(y_i - \bar{y})}{\sum_{i = 1}^{n}(x_i - \bar{x})^2}
\end{align*}\]</span></p>
<p> </p>
<p><span class="math display">\[\begin{align*}
b_0 = \bar{y} - b_1\bar{x}
\end{align*}\]</span></p>
<p> </p>
<p>Now when we know the best estimates of the model parameters, let’s calculate their values. First, we will do it manually using the formulas:</p>
<div class="sourceCode" id="cb499"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="va">x</span> <span class="op">&lt;-</span> <span class="va">dataset1</span><span class="op">$</span><span class="va">Height</span></span>
<span></span>
<span><span class="va">y</span> <span class="op">&lt;-</span> <span class="va">dataset1</span><span class="op">$</span><span class="va">LungCap</span></span>
<span></span>
<span><span class="va">Sxy</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">(</span><span class="va">x</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span> <span class="op">*</span> <span class="op">(</span><span class="va">y</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">Sxx</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">(</span><span class="va">x</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span> <span class="op">^</span> <span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="va">Syy</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">(</span><span class="va">y</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span><span class="op">)</span> <span class="op">^</span> <span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="va">b_1</span> <span class="op">&lt;-</span> <span class="va">Sxy</span> <span class="op">/</span> <span class="va">Sxx</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">b_1</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 0.3371566</span></span>
<span></span>
<span><span class="va">b_0</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span> <span class="op">-</span> <span class="va">b_1</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">b_0</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] -13.99683</span></span></code></pre></div>
<p>Thus, a fitted function for our fitted model is given by</p>
<p> </p>
<p><span class="math display">\[\begin{align*}
\hat{Y} = -13.996 + 0.337 X
\end{align*}\]</span></p>
<p>Or, specifically</p>
<p><span class="math display">\[\begin{align*}
\hat{Lung Capacity} = -13.996 + 0.337 Height
\end{align*}\]</span></p>
<p> </p>
<p>We can interpret the model estimates as follows:</p>
<p>We can expect the mean value of <code>lung capacity</code> to increase by 0.337 units per unit increase in the <code>Height</code> predictor.</p>
<p>In given context, it makes no sense to interpret the intercept as the scope of the model does not include <span class="math inline">\(X = 0\)</span> (you cannot have a patient with <code>Height = 0</code>).</p>
<p>Now, instead of doing calculations manually we can use the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function:</p>
<div class="sourceCode" id="cb500"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="va">model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">LungCap</span> <span class="op">~</span> <span class="va">Height</span>, data <span class="op">=</span> <span class="va">dataset1</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; lm(formula = LungCap ~ Height, data = dataset1)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Residuals:</span></span>
<span><span class="co">#&gt;     Min      1Q  Median      3Q     Max </span></span>
<span><span class="co">#&gt; -3.3619 -0.7014 -0.0032  0.7787  3.2938 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients:</span></span>
<span><span class="co">#&gt;               Estimate Std. Error t value Pr(&gt;|t|)    </span></span>
<span><span class="co">#&gt; (Intercept) -13.996829   0.367451  -38.09   &lt;2e-16 ***</span></span>
<span><span class="co">#&gt; Height        0.337157   0.005633   59.86   &lt;2e-16 ***</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  </span></span>
<span><span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Residual standard error: 1.092 on 723 degrees of freedom</span></span>
<span><span class="co">#&gt; Multiple R-squared:  0.8321, Adjusted R-squared:  0.8319 </span></span>
<span><span class="co">#&gt; F-statistic:  3583 on 1 and 723 DF,  p-value: &lt; 2.2e-16</span></span></code></pre></div>
<p>The <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> function provides a model summary (we will come back to it shortly).</p>
<p>Now we can visualize our results and plot the fitted regression line:</p>
<div class="sourceCode" id="cb501"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="va">gg</span> <span class="op">+</span></span>
<span>  </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">'lm'</span><span class="op">)</span></span>
<span><span class="co">#&gt; `geom_smooth()` using formula = 'y ~ x'</span></span></code></pre></div>
<div class="inline-figure"><img src="Module_14_files/figure-html/unnamed-chunk-8-1.png" width="672"></div>
<p>Set <code>se = FALSE</code> if you want to remove the confidence band around the regression line:</p>
<div class="sourceCode" id="cb502"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="va">gg</span> <span class="op">+</span></span>
<span>  </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">'lm'</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="co">#&gt; `geom_smooth()` using formula = 'y ~ x'</span></span></code></pre></div>
<div class="inline-figure"><img src="Module_14_files/figure-html/unnamed-chunk-9-1.png" width="672"></div>
<p> </p>
</div>
<div id="making-predictions" class="section level4 unnumbered">
<h4>Making Predictions<a class="anchor" aria-label="anchor" href="#making-predictions"><i class="fas fa-link"></i></a>
</h4>
<p>We can now utilize our fitted model to make predictions. Once again, we first do it manually, then present an R function. Suppose based on the fitted model you want to predict what would the mean lung capacity be for a patient with <span class="math inline">\(Height = 75\)</span>?</p>
<p>To do so, we simply plug this value into the model and calculate the corresponding predicted value:</p>
<p><span class="math display">\[\begin{align*}
\hat{Lung Capacity} = -13.996 + 0.337 Height = -13.996 + 0.337\times 75 = 11.289
\end{align*}\]</span></p>
<p>Thus, the expected lung capacity for a patient with <code>Height = 75</code> is 11.289. Most of the time, you will want to make predictions for multiple values, and the number of inputs might be quite large. So instead of doing it manually, you can use the <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> function. You need to pass the fitted model object to the function and values of the predictor variable that you are trying to make predictions for:</p>
<div class="sourceCode" id="cb503"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">model</span>, <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>Height <span class="op">=</span> <span class="fl">75</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt;        1 </span></span>
<span><span class="co">#&gt; 11.28991</span></span></code></pre></div>
<p>You can even make predictions for multiple values. For example let’s calculate the expected mean lung capacity for <code>Height = 67.5</code>, <code>Height = 64</code>, and <code>Height = 53.8</code>:</p>
<div class="sourceCode" id="cb504"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">model</span>, <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>Height <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">67.5</span>, <span class="fl">64</span>, <span class="fl">53.8</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt;        1        2        3 </span></span>
<span><span class="co">#&gt; 8.761240 7.581192 4.142195</span></span></code></pre></div>
<p><code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> function can also be used to construct confidence interval. We will come back to this function later.</p>
<p> </p>
</div>
<div id="residuals" class="section level4 unnumbered">
<h4>Residuals<a class="anchor" aria-label="anchor" href="#residuals"><i class="fas fa-link"></i></a>
</h4>
<p>If we think of our model as “Response = Prediction + Error,” we can then write it as</p>
<p> </p>
<p><span class="math display">\[\begin{align*}
Y = \hat{Y} + e
\end{align*}\]</span></p>
<p>We then define a <strong>residual</strong> to be the observed value minus the predicted value:</p>
<p> </p>
<p><span class="math display">\[\begin{align*}
e = Y - \hat{Y}
\end{align*}\]</span></p>
<p>Residuals play a crucial role in a model building process and they are used in many statistical procedures. To obtained residuals for your data, use <code><a href="https://rdrr.io/r/stats/residuals.html">residuals()</a></code> function (we will display the first 10 residuals as the dataset is large and displaying all residuals will take up much space):</p>
<div class="sourceCode" id="cb505"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="co"># Obtaining first 10 residuals</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">10</span><span class="op">]</span>  </span>
<span><span class="co">#&gt;           1           2           3           4           5 </span></span>
<span><span class="co">#&gt; -0.46559420 -1.06376699  0.04701586  1.18371232 -0.38738003 </span></span>
<span><span class="co">#&gt;           6           7           8           9          10 </span></span>
<span><span class="co">#&gt;  0.43073814 -2.39518208 -2.41399374 -0.89770940  0.83715986</span></span></code></pre></div>
<p>It is a good idea to bind together the residuals and the predictor variable in one data frame so that you know what residual corresponds to what predictor value (values of the independent variable, <strong>not predictions!</strong>):</p>
<div class="sourceCode" id="cb506"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="co"># Obtaining first 10 residuals and corresponding predictor values</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>Height <span class="op">=</span> <span class="va">dataset1</span><span class="op">$</span><span class="va">Height</span>, Residuals <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">10</span>, <span class="op">]</span></span>
<span><span class="co">#&gt;    Height   Residuals</span></span>
<span><span class="co">#&gt; 1    62.1 -0.46559420</span></span>
<span><span class="co">#&gt; 2    74.7 -1.06376699</span></span>
<span><span class="co">#&gt; 3    69.7  0.04701586</span></span>
<span><span class="co">#&gt; 4    71.0  1.18371232</span></span>
<span><span class="co">#&gt; 5    56.9 -0.38738003</span></span>
<span><span class="co">#&gt; 6    58.7  0.43073814</span></span>
<span><span class="co">#&gt; 7    63.3 -2.39518208</span></span>
<span><span class="co">#&gt; 8    70.4 -2.41399374</span></span>
<span><span class="co">#&gt; 9    70.5 -0.89770940</span></span>
<span><span class="co">#&gt; 10   59.2  0.83715986</span></span></code></pre></div>
<p>One of the main properties of residuals is that their summation is equal to zero. This property is used to derive some other important features of linear regression models. Let’s show that the residuals for our model indeed add up to zero:</p>
<div class="sourceCode" id="cb507"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] -2.658464e-14</span></span></code></pre></div>
<p> </p>
</div>
<div id="variance-estimation" class="section level4 unnumbered">
<h4>Variance Estimation<a class="anchor" aria-label="anchor" href="#variance-estimation"><i class="fas fa-link"></i></a>
</h4>
<p>We will now use the residuals to estimate the model variance, <span class="math inline">\(\sigma^2\)</span>. The best estimate of the model variance <span class="math inline">\(\sigma^2\)</span> (derivations once again are omitted) is the <strong>Error Mean Square (MSE)</strong> given by</p>
<p> </p>
<p><span class="math display">\[\begin{align*}
MSE = \frac{\sum_{i = 1}^{n}(Y_i - \hat{Y}_i)^2}{n-2} = \frac{SSE}{n-2} = \frac{\sum Residuals^2}{n-2}
\end{align*}\]</span></p>
<p> </p>
<p>Let’s estimate the model variance based on our data. First, let’s do it manually:</p>
<div class="sourceCode" id="cb508"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span><span class="op">/</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">dataset1</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">-</span><span class="fl">2</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 1.191535</span></span></code></pre></div>
<p>The output of the <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> function includes MSE, that is, an estimate of the model variance. Thus, it can be used for variance estimation:</p>
<div class="sourceCode" id="cb509"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span></span>
<span><span class="co">#&gt; Analysis of Variance Table</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Response: LungCap</span></span>
<span><span class="co">#&gt;            Df Sum Sq Mean Sq F value    Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; Height      1 4269.0  4269.0  3582.8 &lt; 2.2e-16 ***</span></span>
<span><span class="co">#&gt; Residuals 723  861.5     1.2                      </span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  </span></span>
<span><span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code></pre></div>
<p>In this output the value in the intersection of the <code>Mean.Sq</code> column and the <code>Residuals</code> row is MSE. Here, it is equal to 1.2.</p>
<p> </p>
</div>
<div id="lm-useful-functions" class="section level4 unnumbered">
<h4>lm(): Useful Functions<a class="anchor" aria-label="anchor" href="#lm-useful-functions"><i class="fas fa-link"></i></a>
</h4>
<p>In this section I would like to share with you some useful functions that will allow you extract important information/features from your fitted model.</p>
<p><strong>summary()</strong></p>
<p><code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> function, as you’ve already seen, summarizes the fitted model:</p>
<div class="sourceCode" id="cb510"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; lm(formula = LungCap ~ Height, data = dataset1)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Residuals:</span></span>
<span><span class="co">#&gt;     Min      1Q  Median      3Q     Max </span></span>
<span><span class="co">#&gt; -3.3619 -0.7014 -0.0032  0.7787  3.2938 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients:</span></span>
<span><span class="co">#&gt;               Estimate Std. Error t value Pr(&gt;|t|)    </span></span>
<span><span class="co">#&gt; (Intercept) -13.996829   0.367451  -38.09   &lt;2e-16 ***</span></span>
<span><span class="co">#&gt; Height        0.337157   0.005633   59.86   &lt;2e-16 ***</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  </span></span>
<span><span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Residual standard error: 1.092 on 723 degrees of freedom</span></span>
<span><span class="co">#&gt; Multiple R-squared:  0.8321, Adjusted R-squared:  0.8319 </span></span>
<span><span class="co">#&gt; F-statistic:  3583 on 1 and 723 DF,  p-value: &lt; 2.2e-16</span></span></code></pre></div>
<p>It contains all sorts of information presented in one output. We will discuss them more in detail later on.</p>
<p><strong>coef()</strong></p>
<p>If your goal is to extract just the model coefficients (estimates), then use the <code><a href="https://rdrr.io/r/stats/coef.html">coef()</a></code> function:</p>
<div class="sourceCode" id="cb511"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span></span>
<span><span class="co">#&gt; (Intercept)      Height </span></span>
<span><span class="co">#&gt; -13.9968289   0.3371566</span></span></code></pre></div>
<p><strong>resid()</strong></p>
<p>The <code><a href="https://rdrr.io/r/stats/residuals.html">resid()</a></code> function is the same as the <code><a href="https://rdrr.io/r/stats/residuals.html">residuals()</a></code> functions and displays residuals for the fitted model:</p>
<div class="sourceCode" id="cb512"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="co"># Obtaining residuals for the first 10 observations in the dataset</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">resid</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">10</span><span class="op">]</span></span>
<span><span class="co">#&gt;           1           2           3           4           5 </span></span>
<span><span class="co">#&gt; -0.46559420 -1.06376699  0.04701586  1.18371232 -0.38738003 </span></span>
<span><span class="co">#&gt;           6           7           8           9          10 </span></span>
<span><span class="co">#&gt;  0.43073814 -2.39518208 -2.41399374 -0.89770940  0.83715986</span></span></code></pre></div>
<p><strong>fitted()</strong></p>
<p>The <code><a href="https://rdrr.io/r/stats/fitted.values.html">fitted()</a></code> function is used to obtain the fitted values:</p>
<div class="sourceCode" id="cb513"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="co"># Obtaining fitted values for the first 10 observations in the dataset</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">10</span><span class="op">]</span></span>
<span><span class="co">#&gt;         1         2         3         4         5         6 </span></span>
<span><span class="co">#&gt;  6.940594 11.188767  9.502984  9.941288  5.187380  5.794262 </span></span>
<span><span class="co">#&gt;         7         8         9        10 </span></span>
<span><span class="co">#&gt;  7.345182  9.738994  9.772709  5.962840</span></span></code></pre></div>
<p>As you understand, there is relationship among the actual response values, fitted values, and the residuals:</p>
<div class="sourceCode" id="cb514"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="va">actual</span> <span class="op">&lt;-</span> <span class="va">dataset1</span><span class="op">$</span><span class="va">LungCap</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">10</span><span class="op">]</span></span>
<span></span>
<span><span class="va">fitted</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">10</span><span class="op">]</span></span>
<span></span>
<span><span class="va">residuals</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">resid</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">10</span><span class="op">]</span></span>
<span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">residuals</span>, <span class="va">actual</span> <span class="op">-</span> <span class="va">fitted</span><span class="op">)</span></span>
<span><span class="co">#&gt;      residuals actual...fitted</span></span>
<span><span class="co">#&gt; 1  -0.46559420     -0.46559420</span></span>
<span><span class="co">#&gt; 2  -1.06376699     -1.06376699</span></span>
<span><span class="co">#&gt; 3   0.04701586      0.04701586</span></span>
<span><span class="co">#&gt; 4   1.18371232      1.18371232</span></span>
<span><span class="co">#&gt; 5  -0.38738003     -0.38738003</span></span>
<span><span class="co">#&gt; 6   0.43073814      0.43073814</span></span>
<span><span class="co">#&gt; 7  -2.39518208     -2.39518208</span></span>
<span><span class="co">#&gt; 8  -2.41399374     -2.41399374</span></span>
<span><span class="co">#&gt; 9  -0.89770940     -0.89770940</span></span>
<span><span class="co">#&gt; 10  0.83715986      0.83715986</span></span></code></pre></div>
<p> </p>
</div>
<div id="confidence-interval-for-beta_1" class="section level4 unnumbered">
<h4>Confidence interval for <span class="math inline">\(\beta_{1}\)</span><a class="anchor" aria-label="anchor" href="#confidence-interval-for-beta_1"><i class="fas fa-link"></i></a>
</h4>
<p>For illustrative purposes, we will be using the Muscle Mass data set (available on Courseworks):</p>
<p>A person’s muscle mass is expected to decrease with age. To explore this relationship in women, a nutritionist randomly selected 15 women from each 10-year age group, beginning with age 40 and ending with age 79. She recorded their Age (predictor) and a measure of muscle mass (MM, response).</p>
<p>Now let’s run a simple linear regression model. You can use “lm()” function:</p>
<div class="sourceCode" id="cb515"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="va">model</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">MM</span> <span class="op">~</span> <span class="va">Age</span>, data <span class="op">=</span> <span class="va">mydata</span><span class="op">)</span></span></code></pre></div>
<p>To check the summary of the model, use “summary()” function:</p>
<div class="sourceCode" id="cb516"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; lm(formula = MM ~ Age, data = mydata)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Residuals:</span></span>
<span><span class="co">#&gt;      Min       1Q   Median       3Q      Max </span></span>
<span><span class="co">#&gt; -16.1368  -6.1968  -0.5969   6.7607  23.4731 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients:</span></span>
<span><span class="co">#&gt;             Estimate Std. Error t value Pr(&gt;|t|)    </span></span>
<span><span class="co">#&gt; (Intercept) 156.3466     5.5123   28.36   &lt;2e-16 ***</span></span>
<span><span class="co">#&gt; Age          -1.1900     0.0902  -13.19   &lt;2e-16 ***</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  </span></span>
<span><span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Residual standard error: 8.173 on 58 degrees of freedom</span></span>
<span><span class="co">#&gt; Multiple R-squared:  0.7501, Adjusted R-squared:  0.7458 </span></span>
<span><span class="co">#&gt; F-statistic: 174.1 on 1 and 58 DF,  p-value: &lt; 2.2e-16</span></span></code></pre></div>
<p>The estimates of the model parameters can be found under “Coefficients” in the “Estimate” column. For example, the estimate of the slope, that is, the estimated coefficient associated with the “Age” predictor is equal to -1.19. Similarly, the estimate of the intercept is 156.3466.</p>
<p>You can construct a confidence interval and test hypothesis regarding the <span class="math inline">\(\beta_{1}\)</span> by either using R functions or doing it manually. We will consider both ways. Let’s start with R codes.</p>
<p>To find a confidence interval for the slope, given <span class="math inline">\(\alpha = 0.05\)</span> significance level, use the following function:</p>
<div class="sourceCode" id="cb517"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">model</span>, <span class="st">"Age"</span>, level <span class="op">=</span> <span class="fl">0.95</span><span class="op">)</span></span>
<span><span class="co">#&gt;         2.5 %    97.5 %</span></span>
<span><span class="co">#&gt; Age -1.370545 -1.009446</span></span></code></pre></div>
<p>You can observe that this function computes lower and upper bounds of the confidence interval for the specified level of significance <span class="math inline">\(\alpha\)</span>. The function has three arguments: first is the model name (whatever name you give to your model), the predictor’s name, and the confidence level).</p>
<p>Now, let’s do it manually. A confidence interval for the slope can be computed by</p>
<p><span class="math display">\[\begin{align*}
b_{1} \pm t(1-\alpha/2; n-2) \times s(b_{1})
\end{align*}\]</span></p>
<p>We found that the estimate of the slope is <span class="math inline">\(b_{1}  = -1.19\)</span>. <span class="math inline">\(s(b_{1})\)</span> is the standard error of the estimate and can be found in the model summary under “Coefficients” in the “Std. Error” column. For this example <span class="math inline">\(s(b_{1}) = 0.0902\)</span>. Finally, for <span class="math inline">\(\alpha = 0.05\)</span>, <span class="math inline">\(t(1-\alpha/2; n-2) = t(0.975; 58)\)</span> and can be found by</p>
<div class="sourceCode" id="cb518"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="fl">0.975</span>, <span class="fl">58</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 2.001717</span></span></code></pre></div>
<p>So putting everything together we get</p>
<p><span class="math display">\[\begin{align*}
-1.19 \pm 2.0017 \times 0.0902
\end{align*}\]</span></p>
<p> </p>
</div>
<div id="testing-h_0-beta_1-0-quad-vs-quad-h_a-beta_1-neq-0-via-t-test" class="section level4 unnumbered">
<h4>Testing <span class="math inline">\(H_{0}: \beta_{1} = 0  \quad vs \quad H_{a}: \beta_{1} \neq 0\)</span> via t-test<a class="anchor" aria-label="anchor" href="#testing-h_0-beta_1-0-quad-vs-quad-h_a-beta_1-neq-0-via-t-test"><i class="fas fa-link"></i></a>
</h4>
<p>Now let’s perform hypothesis testing concerning the following hypotheses:</p>
<p><span class="math display">\[\begin{align*}
H_{0}: \beta_{1} = 0  \quad vs \quad H_{a}: \beta_{1} \neq 0
\end{align*}\]</span></p>
<p>First let’s do it by performing t-test. The easiest way is to just check the summary output of the model: here the test statistic <span class="math inline">\(t^{*}\)</span> can be found under “Coefficients” in the “t value” column. It is -13.19 for our case. Then the corresponding P-value is given at the intersection of “Pr(&gt;|t|)” column and “Age” row, and it is 0 for our example (basically, &lt;2e-16 is a very very small number and can be treated as 0). So based on this P-value you can make a conclusion about the significance of the predictor.</p>
<p>We can perform the same procedure manually. To do so, let’s consider another example. Suppose you want to test the following hypothesis:</p>
<p><span class="math display">\[\begin{align*}
H_{0}: \beta_{1} = 2  \quad vs \quad H_{a}: \beta_{1} \neq 2
\end{align*}\]</span></p>
<p>First let’s find the the test statistic <span class="math inline">\(t^{*}\)</span>:</p>
<p><span class="math display">\[\begin{align*}
t^{*} = \frac{b_{1} - 2}{s(b_{1})}
\end{align*}\]</span></p>
<p>For our example it is <span class="math inline">\(t^{*} = \frac{-1.19 - 2}{0.0902} = -35.3656\)</span>. As we know <span class="math inline">\(t^{*} \sim t(n-2)\)</span>. Then the corresponding P-value can be computed by finding the probability of two tails beyond <span class="math inline">\(\pm|t^{*}|\)</span>. So</p>
<div class="sourceCode" id="cb519"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="fl">2</span><span class="op">*</span><span class="op">(</span><span class="fl">1</span><span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">pt</a></span><span class="op">(</span><span class="fl">35.3656</span>, <span class="fl">58</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 0</span></span></code></pre></div>
<p>As you can see we get the same result as reported in the table. Note, for one-sided test, you don’t multiply the quatity by 2 and you have to pick the side that corresponds to your hypothesis.</p>
<p> </p>
</div>
<div id="testing-h_0-beta_1-0-quad-vs-quad-h_a-beta_1-neq-0-via-f-test" class="section level4 unnumbered">
<h4>Testing <span class="math inline">\(H_{0}: \beta_{1} = 0  \quad vs \quad H_{a}: \beta_{1} \neq 0\)</span> via F-test<a class="anchor" aria-label="anchor" href="#testing-h_0-beta_1-0-quad-vs-quad-h_a-beta_1-neq-0-via-f-test"><i class="fas fa-link"></i></a>
</h4>
<p>Now let’s consider another way of testing <span class="math inline">\(H_{0}: \beta_{1} = 0  \quad vs \quad H_{a}: \beta_{1} \neq 0\)</span>, which is F-test. To do so, let’s obtain an ANOVA table:</p>
<div class="sourceCode" id="cb520"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span></span>
<span><span class="co">#&gt; Analysis of Variance Table</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Response: MM</span></span>
<span><span class="co">#&gt;           Df  Sum Sq Mean Sq F value    Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; Age        1 11627.5 11627.5  174.06 &lt; 2.2e-16 ***</span></span>
<span><span class="co">#&gt; Residuals 58  3874.4    66.8                      </span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  </span></span>
<span><span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code></pre></div>
<p>The output above helps you set up the anova table: it provides values of degrees of freedom, sum of squares, and mean sum of squares for Regression (stated as Age in the table) and error (stated as residuals).</p>
<p>Anova table also provides a test statistic for the F-test, which is 174.06 (check whether it is indeed equal to MSR/MSE) and is given in the “F value” column. Then the corresponding P-value will be provided in the “Pr(&gt;F)” column and is 0.</p>
</div>
<div id="confidence-interval-for-mean-response" class="section level4 unnumbered">
<h4>Confidence interval for mean response<a class="anchor" aria-label="anchor" href="#confidence-interval-for-mean-response"><i class="fas fa-link"></i></a>
</h4>
<p>Now we will construct a 95% confidence interval for the mean muscle mass of women at age of 20. To do so, use the following formula:</p>
<div class="sourceCode" id="cb521"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">model</span>, <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>Age <span class="op">=</span> <span class="fl">20</span><span class="op">)</span>, interval <span class="op">=</span> <span class="st">"confidence"</span>, level <span class="op">=</span> <span class="fl">0.95</span><span class="op">)</span></span>
<span><span class="co">#&gt;        fit     lwr      upr</span></span>
<span><span class="co">#&gt; 1 132.5467 125.025 140.0683</span></span></code></pre></div>
<p>The output above gives an estimate of the mean response (132.5467 in this case) and lower and upper boundaries for the confidence interval.</p>
</div>
<div id="prediction-interval-for-mean-response" class="section level4 unnumbered">
<h4>Prediction interval for mean response<a class="anchor" aria-label="anchor" href="#prediction-interval-for-mean-response"><i class="fas fa-link"></i></a>
</h4>
<p>Similarly, we can find a prediction interval for the mean muscle mass for women at age of 20 (remember what is the difference between confidence and prediction intervals?). To do so, use the following formula:</p>
<div class="sourceCode" id="cb522"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">model</span>, <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>Age <span class="op">=</span> <span class="fl">20</span><span class="op">)</span>, interval <span class="op">=</span> <span class="st">"prediction"</span>, level <span class="op">=</span> <span class="fl">0.95</span><span class="op">)</span></span>
<span><span class="co">#&gt;        fit      lwr      upr</span></span>
<span><span class="co">#&gt; 1 132.5467 114.5401 150.5532</span></span></code></pre></div>
<p><strong>Note:</strong> Many topics discussed in this module might be unfamiliar to you and that’s ok. You will take a <strong>STAT 5205: Linear Regression Models</strong> class in the upcoming fall semester, where you will be exposed to these and other related topics more in detail. As of now, it is enough to know these basic R functions.</p>

</div>
</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="module-13.html">Module 13</a></div>
<div class="next"><a href="problem-set-4.html">Problem Set 4</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#module-14">Module 14</a></li>
<li>
<a class="nav-link" href="#modeling">Modeling</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#introduction-2">Introduction</a></li>
<li><a class="nav-link" href="#simple-linear-regression-slr-model">Simple Linear Regression (SLR) Model</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/rstudio/bookdown-demo/blob/master/Module_14.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/rstudio/bookdown-demo/edit/master/Module_14.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Summer R Bootcamp</strong>" was written by Alex Pijyan. It was last built on 2025-07-28.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
